# This file is used by `docker-compose up -d`

services:
  appx:
    # Result of container image created by `docker build`
    image: appx
    # Format: Host:Container ; It means expose to port 5000 on the host level, and forward the traffic to port 5000 inside container
    ports:
      - "5000:5000"
    # Automatically start container after host reboot
    restart: always
